# Generated by Django 4.2.7 on 2025-10-09 09:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('order_number', models.CharField(help_text='Numéro unique de la commande', max_length=50, verbose_name='Numéro de commande')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('confirmed', 'Confirmée'), ('processing', 'En cours'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', help_text='Statut de la commande', max_length=20, verbose_name='Statut')),
                ('order_date', models.DateTimeField(help_text='Date et heure de la commande', verbose_name='Date de commande')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Date de livraison prévue', null=True, verbose_name='Date de livraison')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sous-total HT de la commande', max_digits=10, verbose_name='Sous-total')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Taux de TVA en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Taux de TVA')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la TVA', max_digits=10, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total TTC de la commande', max_digits=10, verbose_name='Total TTC')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taux de remise en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Taux de remise')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la remise', max_digits=10, verbose_name='Montant de remise')),
                ('notes', models.TextField(blank=True, help_text='Notes sur la commande', null=True, verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, help_text='Notes internes (non visibles par le client)', null=True, verbose_name='Notes internes')),
                ('company', models.ForeignKey(help_text='Entreprise propriétaire de la commande', on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('customer', models.ForeignKey(help_text='Client de la commande', on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Client')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a créé la commande', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('invoice_number', models.CharField(help_text='Numéro unique de la facture', max_length=50, verbose_name='Numéro de facture')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', help_text='Statut de la facture', max_length=20, verbose_name='Statut')),
                ('invoice_date', models.DateTimeField(help_text='Date de la facture', verbose_name='Date de facture')),
                ('due_date', models.DateTimeField(help_text="Date d'échéance de paiement", verbose_name="Date d'échéance")),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sous-total HT de la facture', max_digits=10, verbose_name='Sous-total')),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Taux de TVA en pourcentage', max_digits=5, verbose_name='Taux de TVA')),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Montant de la TVA', max_digits=10, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total TTC de la facture', max_digits=10, verbose_name='Total TTC')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant déjà payé', max_digits=10, verbose_name='Montant payé')),
                ('remaining_amount', models.DecimalField(decimal_places=2, help_text='Montant restant à payer', max_digits=10, verbose_name='Montant restant')),
                ('notes', models.TextField(blank=True, help_text='Notes sur la facture', null=True, verbose_name='Notes')),
                ('company', models.ForeignKey(help_text='Entreprise propriétaire de la facture', on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('order', models.OneToOneField(help_text='Commande facturée', on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.order', verbose_name='Commande')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a créé la facture', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('proforma_number', models.CharField(help_text='Numéro unique du devis', max_length=50, unique=True, verbose_name='Numéro de devis')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Rejeté'), ('expired', 'Expiré')], default='draft', help_text='Statut du devis', max_length=20, verbose_name='Statut')),
                ('proforma_date', models.DateTimeField(help_text='Date du devis', verbose_name='Date du devis')),
                ('valid_until', models.DateTimeField(help_text='Date de validité du devis', verbose_name="Valide jusqu'au")),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sous-total HT du devis', max_digits=10, verbose_name='Sous-total')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Taux de TVA en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Taux de TVA')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la TVA', max_digits=10, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total TTC du devis', max_digits=10, verbose_name='Total TTC')),
                ('notes', models.TextField(blank=True, help_text='Notes sur le devis', null=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(help_text='Client du devis', on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Client')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a créé le devis', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['proforma_number'], name='sales_profo_proform_a08359_idx'), models.Index(fields=['customer', 'status'], name='sales_profo_custome_8fdf98_idx'), models.Index(fields=['proforma_date'], name='sales_profo_proform_5f2b16_idx'), models.Index(fields=['valid_until'], name='sales_profo_valid_u_182861_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('check', 'Chèque'), ('bank_transfer', 'Virement bancaire'), ('credit_card', 'Carte de crédit'), ('paypal', 'PayPal'), ('other', 'Autre')], help_text='Méthode de paiement utilisée', max_length=20, verbose_name='Méthode de paiement')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant du paiement', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('payment_date', models.DateTimeField(help_text='Date du paiement', verbose_name='Date de paiement')),
                ('reference', models.CharField(blank=True, help_text='Référence du paiement (numéro de chèque, virement, etc.)', max_length=100, null=True, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, help_text='Notes sur le paiement', null=True, verbose_name='Notes')),
                ('invoice', models.ForeignKey(help_text='Facture payée', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.invoice', verbose_name='Facture')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a enregistré le paiement', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['invoice', 'payment_date'], name='sales_payme_invoice_220c36_idx'), models.Index(fields=['payment_method'], name='sales_payme_payment_b55c21_idx'), models.Index(fields=['payment_date'], name='sales_payme_payment_05f128_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('quantity', models.PositiveIntegerField(help_text='Quantité commandée', verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire HT', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix unitaire')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taux de remise en pourcentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Taux de remise')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la remise', max_digits=10, verbose_name='Montant de remise')),
                ('total_price', models.DecimalField(decimal_places=2, help_text="Prix total HT de l'article", max_digits=10, verbose_name='Prix total')),
                ('company', models.ForeignKey(help_text="Entreprise propriétaire de l'article", on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('order', models.ForeignKey(help_text='Commande parente', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='Commande')),
                ('product', models.ForeignKey(help_text='Produit commandé', on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Produit')),
                ('variant', models.ForeignKey(blank=True, help_text='Variante du produit (optionnel)', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['company'], name='sales_order_company_cc4f08_idx'), models.Index(fields=['order', 'product'], name='sales_order_order_i_3655c0_idx'), models.Index(fields=['product'], name='sales_order_product_138dad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company'], name='sales_order_company_6f34a0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='sales_order_order_n_1515f9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='sales_order_custome_21cf73_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='sales_order_order_d_0a2432_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='sales_order_status_2602a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('company', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company'], name='sales_invoi_company_bbd884_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='sales_invoi_invoice_51f3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='sales_invoi_status_4e3758_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='sales_invoi_invoice_b7f3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='sales_invoi_due_dat_a262a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'invoice_number')},
        ),
    ]
