# Generated by Django 4.2.7 on 2025-10-09 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('first_name', models.CharField(help_text='Prénom du client', max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(help_text='Nom de famille du client', max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(help_text='Adresse email du client', max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone du client', max_length=20, null=True, verbose_name='Téléphone')),
                ('client_company', models.CharField(blank=True, help_text="Nom de l'entreprise du client", max_length=200, null=True, verbose_name='Entreprise du client')),
                ('address', models.TextField(blank=True, help_text='Adresse complète du client', null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, help_text='Ville du client', max_length=100, null=True, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, help_text='Code postal du client', max_length=10, null=True, verbose_name='Code postal')),
                ('country', models.CharField(default='France', help_text='Pays du client', max_length=100, verbose_name='Pays')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le client est actif', verbose_name='Actif')),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires sur le client', null=True, verbose_name='Notes')),
                ('company', models.ForeignKey(help_text='Entreprise propriétaire du client', on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['company'], name='customers_c_company_1b63a5_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['last_name', 'first_name'], name='customers_c_last_na_27dbcc_idx'), models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx')],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
