# Generated by Django 4.2.7 on 2025-10-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('report_type', models.CharField(choices=[('inventory', 'Inventaire'), ('movements', 'Mouvements'), ('adjustments', 'Ajustements'), ('alerts', 'Alertes'), ('summary', 'Résumé')], help_text='Type de rapport de stock', max_length=20, verbose_name='Type de rapport')),
                ('title', models.CharField(help_text='Titre du rapport', max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description du rapport', null=True, verbose_name='Description')),
                ('date_from', models.DateField(help_text='Date de début de la période du rapport', verbose_name='Date de début')),
                ('date_to', models.DateField(help_text='Date de fin de la période du rapport', verbose_name='Date de fin')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filtres appliqués au rapport', verbose_name='Filtres')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Données du rapport', verbose_name='Données')),
                ('is_generated', models.BooleanField(default=False, help_text='Indique si le rapport a été généré', verbose_name='Généré')),
                ('generated_at', models.DateTimeField(blank=True, help_text='Date et heure de génération', null=True, verbose_name='Date de génération')),
                ('company', models.ForeignKey(help_text='Entreprise propriétaire du rapport', on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a généré le rapport', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rapport de stock',
                'verbose_name_plural': 'Rapports de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type'], name='stock_stock_report__8d5270_idx'), models.Index(fields=['date_from', 'date_to'], name='stock_stock_date_fr_456a2a_idx'), models.Index(fields=['is_generated'], name='stock_stock_is_gene_b97c70_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('adjustment', 'Ajustement'), ('transfer', 'Transfert'), ('return', 'Retour')], help_text='Type de mouvement de stock', max_length=20, verbose_name='Type de mouvement')),
                ('quantity', models.IntegerField(help_text='Quantité du mouvement (positive pour entrée, négative pour sortie)', verbose_name='Quantité')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Coût unitaire du produit lors du mouvement', max_digits=10, null=True, verbose_name='Coût unitaire')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Coût total du mouvement', max_digits=10, null=True, verbose_name='Coût total')),
                ('reference', models.CharField(blank=True, help_text='Référence du mouvement (numéro de commande, facture, etc.)', max_length=100, null=True, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires sur le mouvement', null=True, verbose_name='Notes')),
                ('is_approved', models.BooleanField(default=True, help_text='Indique si le mouvement est approuvé', verbose_name='Approuvé')),
                ('approved_at', models.DateTimeField(blank=True, help_text="Date et heure d'approbation", null=True, verbose_name="Date d'approbation")),
                ('approved_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a approuvé le mouvement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_movements', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('company', models.ForeignKey(help_text='Entreprise propriétaire du mouvement', on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('product', models.ForeignKey(help_text='Produit concerné par le mouvement', on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produit')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a effectué le mouvement', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('variant', models.ForeignKey(blank=True, help_text='Variante du produit (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='stock_stock_company_8ecc84_idx'), models.Index(fields=['product', 'movement_type'], name='stock_stock_product_06270c_idx'), models.Index(fields=['created_at'], name='stock_stock_created_69d383_idx'), models.Index(fields=['reference'], name='stock_stock_referen_6ee06b_idx'), models.Index(fields=['is_approved'], name='stock_stock_is_appr_94e61c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Stock bas'), ('out_of_stock', 'Rupture de stock'), ('overstock', 'Surstock')], help_text="Type d'alerte de stock", max_length=20, verbose_name="Type d'alerte")),
                ('current_quantity', models.PositiveIntegerField(help_text='Quantité actuelle en stock', verbose_name='Quantité actuelle')),
                ('threshold_quantity', models.PositiveIntegerField(help_text="Quantité seuil pour déclencher l'alerte", verbose_name='Quantité seuil')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'alerte est active", verbose_name='Active')),
                ('is_resolved', models.BooleanField(default=False, help_text="Indique si l'alerte a été résolue", verbose_name='Résolue')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Date et heure de résolution', null=True, verbose_name='Date de résolution')),
                ('company', models.ForeignKey(help_text="Entreprise propriétaire de l'alerte", on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('product', models.ForeignKey(help_text="Produit concerné par l'alerte", on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produit')),
                ('resolved_by', models.ForeignKey(blank=True, help_text="Utilisateur qui a résolu l'alerte", null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
                ('variant', models.ForeignKey(blank=True, help_text='Variante du produit (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Alerte de stock',
                'verbose_name_plural': 'Alertes de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'alert_type'], name='stock_stock_product_5224e4_idx'), models.Index(fields=['is_active', 'is_resolved'], name='stock_stock_is_acti_dda2f8_idx'), models.Index(fields=['created_at'], name='stock_stock_created_4bee90_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('adjustment_type', models.CharField(choices=[('inventory', 'Inventaire'), ('damage', 'Dégâts'), ('theft', 'Vol'), ('expired', 'Périmé'), ('other', 'Autre')], help_text="Type d'ajustement de stock", max_length=20, verbose_name="Type d'ajustement")),
                ('quantity_before', models.PositiveIntegerField(help_text="Quantité en stock avant l'ajustement", verbose_name='Quantité avant')),
                ('quantity_after', models.PositiveIntegerField(help_text="Quantité en stock après l'ajustement", verbose_name='Quantité après')),
                ('adjustment_quantity', models.IntegerField(help_text="Quantité d'ajustement (positive ou négative)", verbose_name="Quantité d'ajustement")),
                ('reason', models.TextField(help_text="Raison de l'ajustement", verbose_name='Raison')),
                ('is_approved', models.BooleanField(default=False, help_text="Indique si l'ajustement est approuvé", verbose_name='Approuvé')),
                ('approved_at', models.DateTimeField(blank=True, help_text="Date et heure d'approbation", null=True, verbose_name="Date d'approbation")),
                ('approved_by', models.ForeignKey(blank=True, help_text="Utilisateur qui a approuvé l'ajustement", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('company', models.ForeignKey(help_text="Entreprise propriétaire de l'ajustement", on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('product', models.ForeignKey(help_text="Produit concerné par l'ajustement", on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Produit')),
                ('user', models.ForeignKey(help_text="Utilisateur qui a effectué l'ajustement", on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('variant', models.ForeignKey(blank=True, help_text='Variante du produit (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Ajustement de stock',
                'verbose_name_plural': 'Ajustements de stock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'adjustment_type'], name='stock_stock_product_f284e8_idx'), models.Index(fields=['created_at'], name='stock_stock_created_e318b7_idx'), models.Index(fields=['is_approved'], name='stock_stock_is_appr_dc00ca_idx')],
            },
        ),
    ]
