# Generated by Django 4.2.7 on 2025-10-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('title', models.CharField(help_text="Titre de l'alerte", max_length=200, verbose_name='Titre')),
                ('message', models.TextField(help_text="Message détaillé de l'alerte", verbose_name='Message')),
                ('alert_type', models.CharField(choices=[('stock_low', 'Stock bas'), ('stock_out', 'Rupture de stock'), ('invoice_overdue', 'Facture en retard'), ('order_pending', 'Commande en attente'), ('payment_failed', 'Paiement échoué'), ('system_error', 'Erreur système'), ('maintenance', 'Maintenance'), ('custom', 'Personnalisée')], help_text="Type d'alerte", max_length=50, verbose_name="Type d'alerte")),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', help_text='Niveau de priorité', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('active', 'Active'), ('read', 'Lue'), ('resolved', 'Résolue'), ('dismissed', 'Ignorée')], default='active', help_text="Statut de l'alerte", max_length=20, verbose_name='Statut')),
                ('is_read', models.BooleanField(default=False, help_text="Indique si l'alerte a été lue", verbose_name='Lue')),
                ('related_object_type', models.CharField(blank=True, help_text="Type de l'objet lié (ex: Order, Invoice, Product)", max_length=100, null=True, verbose_name="Type d'objet lié")),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet lié", null=True, verbose_name="ID de l'objet lié")),
                ('action_url', models.URLField(blank=True, help_text="URL vers l'objet concerné", null=True, verbose_name="URL d'action")),
                ('action_label', models.CharField(blank=True, help_text="Label du bouton d'action", max_length=100, null=True, verbose_name="Label d'action")),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration de l'alerte", null=True, verbose_name="Date d'expiration")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires au format JSON', verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('name', models.CharField(help_text="Nom officiel de l'entreprise", max_length=200, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'entreprise", null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, help_text="Description de l'entreprise", null=True, verbose_name='Description')),
                ('email', models.EmailField(help_text="Adresse email principale de l'entreprise", max_length=255, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone principal', max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, help_text="Adresse complète de l'entreprise", null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, help_text="Ville de l'entreprise", max_length=100, null=True, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, help_text="Code postal de l'entreprise", max_length=10, null=True, verbose_name='Code postal')),
                ('country', models.CharField(default='France', help_text="Pays de l'entreprise", max_length=100, verbose_name='Pays')),
                ('website', models.URLField(blank=True, help_text="Site web de l'entreprise", null=True, verbose_name='Site web')),
                ('tax_number', models.CharField(blank=True, help_text='Numéro de TVA intracommunautaire', max_length=50, null=True, verbose_name='Numéro de TVA')),
                ('registration_number', models.CharField(blank=True, help_text='Numéro SIRET ou équivalent', max_length=50, null=True, verbose_name="Numéro d'enregistrement")),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'entreprise est active", verbose_name='Active')),
                ('settings', models.JSONField(blank=True, default=dict, help_text="Paramètres personnalisés de l'entreprise", verbose_name='Paramètres')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('phone', models.CharField(blank=True, help_text="Numéro de téléphone personnel de l'utilisateur", max_length=20, null=True, verbose_name='Téléphone personnel')),
                ('position', models.CharField(blank=True, help_text="Poste occupé dans l'entreprise", max_length=100, null=True, verbose_name='Poste')),
                ('department', models.CharField(blank=True, help_text="Département de l'utilisateur", max_length=100, null=True, verbose_name='Département')),
                ('hire_date', models.DateField(blank=True, help_text="Date d'embauche dans l'entreprise", null=True, verbose_name="Date d'embauche")),
                ('is_company_admin', models.BooleanField(default=False, help_text="Indique si l'utilisateur est administrateur de l'entreprise", verbose_name="Admin de l'entreprise")),
                ('notes', models.TextField(blank=True, help_text="Notes sur l'utilisateur", null=True, verbose_name='Notes')),
                ('company', models.ForeignKey(help_text="Entreprise de l'utilisateur", on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('user', models.OneToOneField(help_text='Utilisateur associé', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Email de l'utilisateur", max_length=254, verbose_name='Email')),
                ('code', models.CharField(help_text='Code de 6 chiffres', max_length=6, verbose_name='Code de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du code', verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration du code", verbose_name="Date d'expiration")),
                ('is_used', models.BooleanField(default=False, help_text='Indique si le code a été utilisé', verbose_name='Utilisé')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Nombre de tentatives de validation', verbose_name='Tentatives')),
                ('user', models.ForeignKey(help_text='Utilisateur concerné par le reset', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code de reset de mot de passe',
                'verbose_name_plural': 'Codes de reset de mot de passe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('title', models.CharField(help_text='Titre de la notification', max_length=200, verbose_name='Titre')),
                ('message', models.TextField(help_text='Message de la notification', verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('order_created', 'Commande créée'), ('order_updated', 'Commande mise à jour'), ('order_cancelled', 'Commande annulée'), ('invoice_created', 'Facture créée'), ('invoice_paid', 'Facture payée'), ('payment_received', 'Paiement reçu'), ('stock_alert', 'Alerte de stock'), ('user_action', 'Action utilisateur'), ('system_message', 'Message système'), ('reminder', 'Rappel'), ('custom', 'Personnalisée')], help_text='Type de notification', max_length=50, verbose_name='Type de notification')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', help_text='Niveau de priorité', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('unread', 'Non lue'), ('read', 'Lue'), ('archived', 'Archivée')], default='unread', help_text='Statut de la notification', max_length=20, verbose_name='Statut')),
                ('is_read', models.BooleanField(default=False, help_text='Indique si la notification a été lue', verbose_name='Lue')),
                ('related_object_type', models.CharField(blank=True, help_text="Type de l'objet lié (ex: Order, Invoice, Product)", max_length=100, null=True, verbose_name="Type d'objet lié")),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet lié", null=True, verbose_name="ID de l'objet lié")),
                ('action_url', models.URLField(blank=True, help_text="URL vers l'objet concerné", null=True, verbose_name="URL d'action")),
                ('action_label', models.CharField(blank=True, help_text="Label du bouton d'action", max_length=100, null=True, verbose_name="Label d'action")),
                ('read_at', models.DateTimeField(blank=True, help_text='Date à laquelle la notification a été lue', null=True, verbose_name='Date de lecture')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration de la notification", null=True, verbose_name="Date d'expiration")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires au format JSON', verbose_name='Métadonnées')),
                ('user', models.ForeignKey(help_text='Utilisateur destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='common_comp_name_555849_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['email'], name='common_comp_email_7fca9e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='common_comp_is_acti_997d8f_idx'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Utilisateur concerné par l'alerte", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['company'], name='common_user_company_a990db_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_company_admin'], name='common_user_is_comp_c08598_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['hire_date'], name='common_user_hire_da_9be0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['email', 'code'], name='common_pass_email_fa5227_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetcode',
            index=models.Index(fields=['expires_at'], name='common_pass_expires_43e191_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='common_noti_user_id_974fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'priority'], name='common_noti_notific_4414f2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'created_at'], name='common_noti_is_read_879eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='common_noti_expires_dc118c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'status'], name='common_aler_user_id_f23a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'priority'], name='common_aler_alert_t_0290c2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read', 'created_at'], name='common_aler_is_read_c9d607_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['expires_at'], name='common_aler_expires_e24475_idx'),
        ),
    ]
