# Generated by Django 4.2.7 on 2026-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#007bff', help_text="Couleur principale de l'entreprise (format hexadécimal, ex: #007bff)", max_length=7, verbose_name='Couleur principale'),
        ),
    ]
