# Generated by Django 4.2.7 on 2025-10-09 09:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('name', models.CharField(help_text='Nom de la catégorie', max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie', null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Image de la catégorie', null=True, upload_to='categories/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la catégorie est active', verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage de la catégorie", verbose_name='Ordre de tri')),
                ('company', models.ForeignKey(help_text='Entreprise propriétaire de la catégorie', on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('parent', models.ForeignKey(blank=True, help_text='Catégorie parente pour créer une hiérarchie', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('name', models.CharField(help_text='Nom du produit', max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du produit', null=True, verbose_name='Description')),
                ('short_description', models.CharField(blank=True, help_text='Description courte du produit', max_length=500, null=True, verbose_name='Description courte')),
                ('sku', models.CharField(help_text='Code produit unique (SKU)', max_length=100, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, help_text='Code-barres du produit', max_length=100, null=True, unique=True, verbose_name='Code-barres')),
                ('product_type', models.CharField(choices=[('simple', 'Produit simple'), ('variable', 'Produit avec variants'), ('bundle', 'Pack/Lot')], default='simple', help_text='Type de produit', max_length=20, verbose_name='Type de produit')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('discontinued', 'Discontinué'), ('out_of_stock', 'Rupture de stock')], default='active', help_text='Statut du produit', max_length=20, verbose_name='Statut')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix de base du produit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix de revient du produit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix de revient')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Poids du produit en kilogrammes', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Poids (kg)')),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions du produit (L x l x H)', max_length=100, null=True, verbose_name='Dimensions')),
                ('is_digital', models.BooleanField(default=False, help_text="Indique si c'est un produit numérique", verbose_name='Produit numérique')),
                ('is_featured', models.BooleanField(default=False, help_text="Indique si c'est un produit mis en avant", verbose_name='Produit vedette')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500, null=True, verbose_name='Tags')),
                ('meta_title', models.CharField(blank=True, help_text='Titre SEO', max_length=200, null=True, verbose_name='Meta titre')),
                ('meta_description', models.TextField(blank=True, help_text='Description SEO', null=True, verbose_name='Meta description')),
                ('category', models.ForeignKey(help_text='Catégorie du produit', on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Catégorie')),
                ('company', models.ForeignKey(help_text='Entreprise propriétaire du produit', on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('name', models.CharField(help_text='Nom de la variante (ex: Rouge, Taille L)', max_length=100, verbose_name='Nom de la variante')),
                ('sku', models.CharField(help_text='Code unique de la variante', max_length=100, verbose_name='SKU')),
                ('variant_type', models.CharField(choices=[('size', 'Taille'), ('color', 'Couleur'), ('material', 'Matière'), ('style', 'Style'), ('other', 'Autre')], default='other', help_text='Type de variante', max_length=20, verbose_name='Type de variante')),
                ('value', models.CharField(help_text='Valeur de la variante (ex: Rouge, L, Cuir)', max_length=100, verbose_name='Valeur')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Modification du prix par rapport au produit de base', max_digits=10, verbose_name='Modificateur de prix')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Quantité disponible en stock', verbose_name='Quantité en stock')),
                ('min_stock_level', models.PositiveIntegerField(default=0, help_text='Niveau de stock minimum avant alerte', verbose_name='Stock minimum')),
                ('max_stock_level', models.PositiveIntegerField(default=1000, help_text='Niveau de stock maximum', verbose_name='Stock maximum')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la variante est active', verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage de la variante", verbose_name='Ordre de tri')),
                ('company', models.ForeignKey(help_text='Entreprise propriétaire de la variante', on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('product', models.ForeignKey(help_text='Produit parent', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Variante de produit',
                'verbose_name_plural': 'Variantes de produit',
                'ordering': ['product', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['company'], name='inventory_p_company_a98654_idx'), models.Index(fields=['product'], name='inventory_p_product_cc68de_idx'), models.Index(fields=['sku'], name='inventory_p_sku_3e98d7_idx'), models.Index(fields=['is_active'], name='inventory_p_is_acti_5b253b_idx'), models.Index(fields=['stock_quantity'], name='inventory_p_stock_q_ca535b_idx')],
                'unique_together': {('company', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('image', models.ImageField(help_text='Image du produit', upload_to='products/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text="Texte alternatif pour l'accessibilité", max_length=200, null=True, verbose_name='Texte alternatif')),
                ('is_primary', models.BooleanField(default=False, help_text="Indique si c'est l'image principale", verbose_name='Image principale')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage de l'image", verbose_name='Ordre de tri')),
                ('company', models.ForeignKey(help_text="Entreprise propriétaire de l'image", on_delete=django.db.models.deletion.CASCADE, to='common.company', verbose_name='Entreprise')),
                ('product', models.ForeignKey(help_text='Produit associé', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image de produit',
                'verbose_name_plural': 'Images de produit',
                'ordering': ['product', 'sort_order'],
                'indexes': [models.Index(fields=['company'], name='inventory_p_company_0c5705_idx'), models.Index(fields=['product'], name='inventory_p_product_d8ed7d_idx'), models.Index(fields=['is_primary'], name='inventory_p_is_prim_cece5d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='inventory_p_company_b7c0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='inventory_p_barcode_3a77e5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_607069_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='inventory_p_status_2ba142_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='inventory_p_product_3c97c6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='inventory_p_is_feat_06d377_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'sku')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company'], name='inventory_c_company_ddcdb9_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='inventory_c_is_acti_63d81f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='inventory_c_parent__a38b2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'name')},
        ),
    ]
