# Generated by Django 4.2.7 on 2026-04-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['product', 'variant', 'sort_order'], 'verbose_name': 'Image de produit', 'verbose_name_plural': 'Images de produit'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Variant associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.productvariant', verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Produit associé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product', verbose_name='Produit'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['variant'], name='inventory_p_variant_efecff_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product__isnull', False), ('variant__isnull', True)), models.Q(('product__isnull', True), ('variant__isnull', False)), _connector='OR'), name='product_or_variant_required'),
        ),
    ]
