# Generated by Django 4.2.7 on 2025-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('cache_key', models.CharField(help_text='Clé unique pour identifier le cache', max_length=255, unique=True, verbose_name='Clé de cache')),
                ('data', models.JSONField(help_text='Données mises en cache', verbose_name='Données')),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration du cache", verbose_name='Expire à')),
                ('cache_type', models.CharField(choices=[('kpis', 'KPIs'), ('revenue_chart', 'Graphique des revenus'), ('sales_performance', 'Performance des ventes'), ('top_customers', 'Top clients'), ('top_products', 'Top produits'), ('full_data', 'Données complètes')], help_text='Type de données mises en cache', max_length=50, verbose_name='Type de cache')),
            ],
            options={
                'verbose_name': 'Cache Analytics',
                'verbose_name_plural': 'Caches Analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key'], name='analytics_a_cache_k_9a5fb4_idx'), models.Index(fields=['expires_at'], name='analytics_a_expires_4e35a3_idx'), models.Index(fields=['cache_type'], name='analytics_a_cache_t_78d0e5_idx')],
            },
        ),
    ]
