# Generated by Django 4.2.7 on 2025-10-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('name', models.CharField(help_text='Nom lisible de la permission (ex: Voir les clients)', max_length=100, unique=True, verbose_name='Nom de la permission')),
                ('codename', models.CharField(help_text='Code unique de la permission (ex: customers_view)', max_length=100, unique=True, verbose_name='Code de la permission')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la permission', null=True, verbose_name='Description')),
                ('app_label', models.CharField(help_text="Nom de l'application (ex: customers, sales, inventory)", max_length=50, verbose_name='Application')),
                ('action', models.CharField(help_text="Type d'action (ex: view, create, update, delete, manage)", max_length=20, verbose_name='Action')),
                ('resource', models.CharField(help_text='Ressource concernée (ex: customer, order, product, stock)', max_length=50, verbose_name='Ressource')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la permission est active', verbose_name='Active')),
                ('is_system', models.BooleanField(default=False, help_text='Permissions système qui ne peuvent pas être supprimées', verbose_name='Permission système')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['app_label', 'resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('action', models.CharField(choices=[('role_assigned', 'Rôle assigné'), ('role_removed', 'Rôle retiré'), ('permission_granted', 'Permission accordée'), ('permission_revoked', 'Permission révoquée'), ('access_denied', 'Accès refusé'), ('access_granted', 'Accès accordé')], help_text="Type d'action effectuée", max_length=20, verbose_name='Action')),
                ('details', models.JSONField(blank=True, default=dict, help_text="Détails supplémentaires de l'action (JSON)", verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='User Agent du navigateur', null=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Log de permission',
                'verbose_name_plural': 'Logs de permissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('name', models.CharField(help_text='Nom unique du rôle (ex: Admin, Manager, Sales)', max_length=100, unique=True, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du rôle', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le rôle est actif', verbose_name='Actif')),
                ('is_system', models.BooleanField(default=False, help_text='Rôles système qui ne peuvent pas être supprimés', verbose_name='Rôle système')),
                ('level', models.PositiveIntegerField(default=0, help_text='Niveau hiérarchique (0=Admin, 1=Manager, 2=User, 3=Viewer)', verbose_name='Niveau hiérarchique')),
                ('color', models.CharField(default='#007bff', help_text="Couleur hexadécimale pour l'affichage (ex: #007bff)", max_length=7, verbose_name='Couleur')),
                ('icon', models.CharField(blank=True, help_text="Classe CSS de l'icône (ex: fas fa-user-shield)", max_length=50, null=True, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text="Date d'assignation du rôle", verbose_name='Assigné le')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration du rôle (optionnel)", null=True, verbose_name='Expire le')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'assignation est active", verbose_name='Actif')),
                ('notes', models.TextField(blank=True, help_text='Notes sur cette assignation de rôle', null=True, verbose_name='Notes')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a assigné ce rôle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('role', models.ForeignKey(help_text='Rôle assigné', on_delete=django.db.models.deletion.CASCADE, to='permissions.role', verbose_name='Rôle')),
                ('user', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Rôle d'utilisateur",
                'verbose_name_plural': "Rôles d'utilisateurs",
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification', verbose_name='Date de modification')),
                ('granted', models.BooleanField(default=True, help_text='Indique si la permission est accordée ou refusée', verbose_name='Accordée')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions spéciales pour cette permission (JSON)', verbose_name='Conditions')),
                ('notes', models.TextField(blank=True, help_text='Notes sur cette attribution de permission', null=True, verbose_name='Notes')),
                ('permission', models.ForeignKey(help_text='Permission concernée', on_delete=django.db.models.deletion.CASCADE, to='permissions.permission', verbose_name='Permission')),
                ('role', models.ForeignKey(help_text='Rôle concerné', on_delete=django.db.models.deletion.CASCADE, to='permissions.role', verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Permission de rôle',
                'verbose_name_plural': 'Permissions de rôles',
                'ordering': ['role', 'permission'],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='permissions_is_acti_c1045d_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['level'], name='permissions_level_08c3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system'], name='permissions_is_syst_f8c438_idx'),
        ),
        migrations.AddField(
            model_name='permissionlog',
            name='permission',
            field=models.ForeignKey(blank=True, help_text="Permission concernée par l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, to='permissions.permission', verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='permissionlog',
            name='role',
            field=models.ForeignKey(blank=True, help_text="Rôle concerné par l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, to='permissions.role', verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='permissionlog',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text="Utilisateur cible de l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_logs_target', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible'),
        ),
        migrations.AddField(
            model_name='permissionlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Utilisateur concerné par l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['app_label'], name='permissions_app_lab_74c53d_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['action'], name='permissions_action_2cbb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['resource'], name='permissions_resourc_295b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['is_active'], name='permissions_is_acti_9afbb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('app_label', 'resource', 'action')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='permissions_user_id_a31410_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='permissions_role_id_17f4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['expires_at'], name='permissions_expires_f004a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='permissionlog',
            index=models.Index(fields=['user', 'action'], name='permissions_user_id_d31f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionlog',
            index=models.Index(fields=['target_user'], name='permissions_target__0f1b96_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionlog',
            index=models.Index(fields=['created_at'], name='permissions_created_510b60_idx'),
        ),
    ]
